### ISSUE TITLE
Add users to exclude from prompting

### ISSUE THREAD

**Issue by mattstratton** [behaviorbot/request-info#12]
For example, I file a lot of issues in my own repo, and often times they don't need a description (because they are tracking a simple thing). It would be rad if you could either a) provide a list of users to exclude, or b) have a flag to exclude repo owner(s) from the prompt?

**Comment by hiimbex** [comment]
@mattstratton This is a great idea and makes total sense. What about a field added to the `.github/config.yml` file like:
`excludeIssuesCreatedBy: [repoOwner, mainContributors, etc]`
