### ISSUE TITLE
Multiple random messages

### ISSUE THREAD

**Issue by nMustaki** [behaviorbot/request-info#14]
Hello,

this time I won't forget opening an issue before submitting a pr ;-)
I'd like the comment to be picked randomly from a list, in the hope variety would keep the bot both effective and fun.

I would either: 
- create a new configuration array 'requestInfoReplyComments', exclusive with 'requestInfoReplyComment'
- parse 'requestInfoReplyComment' to check if it a string or an array

Would you be interested ?

**Comment by hiimbex** [comment]
Absolutely! This is a great idea. I would prefer to stick to `requestInfoReplyComment` that can optionally be a string or an array for simplicity in the configuration.

Would you be interested in implementing this?

**Comment by nMustaki** [comment]
Sure, I'll give it a try in a few hours


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/
