### ISSUE TITLE
feature request: check body by REGEX

### ISSUE THREAD

**Issue by atian25** [behaviorbot/request-info#23]
RT. allow user to config some regex to check body

**Comment by hiimbex** [comment]
So putting regex in the config.yml? I'd be open to that idea for more custom comparison of issue templates.

cc/ @codebytere @j-f1 for other thoughts? Would this solve your respective "did they fill out the issue template" problems?

**Comment by j-f1** [comment]
> Would this solve your respective "did they fill out the issue template" problems?

👍 Probably

**Comment by codebytere** [comment]
yeah i think this'd be great for us too 😁

**Comment by klaciboy** [comment]
Hello,
 maybe a "beginner" version of this feature would be something like the already existing "default titles" feature. Where you can define keywords which should be exist (or forbidden) in the description. i.e.: "version number", "platform" etc..

 My use case: I have a long template for new issues, where I am asking information about the environment. Platform, version number, flags at startup, config file, etc.

The `checkPullRequestTemplate: true` is almost perfect, but do not cover the case where somebody only fills the "description" part of the issue template, and leaves the rest intact. So do not provide "enough" information.
Regex feature will be great to validate if the whole template was filled properly, but assuming - from the age of this issue - it is hard to implement. A simpler whitelist/backlist solution would be very helpful.

Br,
Laci

**Comment by klaciboy** [comment]
Please tell me you just accidentally closed the issue, before writing ANY answer or reason. That was rude.

**Comment by atian25** [comment]
sorry,  I had forgot what the origin request due to it's 1 year ago. It seems I want to write a bot, but I didn't see the `need more information` notify and miss it, I am sorry for that. Will try to figure it up tomorrow at computer.

**Comment by atian25** [comment]
after some recalled, it seems that my origin purpose is to add some Regex rules config, which could check the issue is matched.

sorry again for closing the issue last night, you are free to reopen it.

**Comment by klaciboy** [comment]
Hello! Thank you for your answer, it was really nice. I will leave the scheduling up to you. Have a nice day!
