### ISSUE TITLE
[Question] What's the correct format I should use for the label?

### ISSUE THREAD

**Issue by jahirfiquitiva** [behaviorbot/request-info#31]
So I have a `needs info` label. Exactly like that, with a blank space. No dashes or anything.

I am wondering what's the correct format to put in the `config.yml` file ... 

Can I put it like:
```yaml
requestInfoLabelToAdd: needs info
```

Or should I do it like:
```yaml
requestInfoLabelToAdd: "needs info"
```

Thanks

**Comment by hiimbex** [comment]
Hi @jahirfiquitiva! The correct way to achieve that would be
```yml
requestInfoLabelToAdd: "needs info"
```
Due to yml file standards/conventions, it will not work without the quotes.

**Comment by jahirfiquitiva** [comment]
@hiimbex 
Awesome. Thank you so much for the help 😀

**Comment by j-f1** [comment]
It looks like [according to the YAML spec](http://yaml.org/spec/1.2/spec.html#id2788859), `requestInfoLabelToAdd: needs info` should be permitted, given that they have an unquoted example `Up, up and away!`.

**Comment by hiimbex** [comment]
hmm, honestly I hate reading the yaml standards so I really can't say for sure. We use some yaml library to interpret for us, so maybe the issue was on their end 🤷🏻‍♀️
