### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by sayed24** [behaviorbot/request-info#38]
I have a stand alone deployment for Github Enterprise. I tested the bot for my account and also under organization which i am a maintainer in it. The bot worked as expected for public repos but for private repos i got this error

```
13:22:45.823Z ERROR event: {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/enterprise/2.13/v3/repos/contents/#get-contents"} (id=77827960-9ca0-11e8-8fc7-3a145c78ba63)
  HttpError: {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/enterprise/2.13/v3/repos/contents/#get-contents"}
      at response.text.then.message (/request-info/node_modules/@octokit/rest/lib/request/request.js:78:19)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  --
  event: {
    "id": "77827960-9ca0-11e8-8fc7-3a145c78ba63",
    "event": "pull_request.opened",
    "repository": "xxxxxxxxxxxxxx/yyyyy",
    "installation": 9
  }
```

```
13:15:45.518Z ERROR event: {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/enterprise/2.13/v3/repos/contents/#get-contents"} (id=7d350540-9c9f-11e8-8a1a-488875117f96)
  HttpError: {"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/enterprise/2.13/v3/repos/contents/#get-contents"}
      at response.text.then.message (/request-info/node_modules/@octokit/rest/lib/request/request.js:78:19)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  --
  event: {
    "id": "7d350540-9c9f-11e8-8a1a-488875117f96",
    "event": "issues.opened",
    "repository": "xxxxxxxxxxxxxx/yyyyy",
    "installation": 9
  }


```

**Comment by hiimbex** [comment]
For private repos, you'll need to add the permission for 'Single File' like so:

<img width="681" alt="screen shot 2018-07-19 at 2 05 44 pm" src="https://user-images.githubusercontent.com/13410355/43966640-4440ad0c-9c77-11e8-8317-ad47a9a3569b.png">

**Comment by sayed24** [comment]
@hiimbex should it be ".github/config.yml" as I am giving permission for file ".github/request-info.yml"

**Comment by hiimbex** [comment]
Yea sorry, old screenshot. It should be `.github/request-info.yml`

**Comment by hiimbex** [comment]
Actually, wait no, request-info by default uses a `.github/config.yml` not `.github/request-info.yml`

**Comment by sayed24** [comment]
@hiimbex how to change the defaults

**Comment by hiimbex** [comment]
What do you mean by the defaults? You need to change this permission in your app settings page

**Comment by sayed24** [comment]
should i change this value https://github.com/behaviorbot/request-info/blob/c2451414a34a26b1b4049dc102d2e7137b9df714/index.js#L24 
or there is another way to change it for my deployment

**Comment by hiimbex** [comment]
Oh if you wanna change the name of the file? I mean you could just rename the actual file, but yea that would work.

**Comment by sayed24** [comment]
@hiimbex ya, I need to change the name of the file. Thanks for your help.
