### ISSUE TITLE
Add a default text

### ISSUE THREAD

**Issue by Mte90** [behaviorbot/request-info#7]
In that way is not required to create a config file only for the message itself

**Comment by hiimbex** [comment]
I'm +1 for this. So in the scenario you are install the bot and have no default titles, even without a confit the bot should still comment something like: 

"The maintainers of this repository would appreciate it if you could provide more information."

What do you think about that as a default message @mte90?

**Comment by Mte90** [comment]
yes!

**Comment by hiimbex** [comment]
👍🏼 I'll implement this later tonight.

**Comment by hiimbex** [comment]
Done! :) see it in action here: https://github.com/probot/test/issues/20!
